services:

  php:
    image: rugolinifr/array-path-selector:1.0.0
    build:
      context: $PWD
      dockerfile: Dockerfile
    command: tail -f /dev/null
    volumes:
      - $PWD:$PWD
    working_dir: $PWD
    networks:
      - enhanced_find_by

networks:
  enhanced_find_by:
    driver: bridge